[app]
    host            = "127.0.0.1:8080"

[configDB]
    host            = "localhost"
    port            = 5432
    user            = "postgres"
    password        = "Postgres2022!"
    dbname          = "postgres"